- name: restart {{ svc__opts_name }}
  systemd:
    name: "{{ svc__opts_systemd_name }}"
    state: restarted
    daemon_reload: yes
  when: svc__opts_enabled

- name: reload {{ svc__opts_name }}
  systemd:
    name: "{{ svc__opts_systemd_name }}"
    state: reloaded
  when: svc__opts_enabled
