- name: restart {{ svc_name }}
  systemd:
    name: "{{ svc_systemd_name }}"
    state: restarted
    daemon_reload: yes

- name: reload {{ svc_name }}
  systemd:
    name: "{{ svc_systemd_name }}"
    state: reloaded
