- name: restart {{ svc_name }}
  systemd:
    name: "{{ svc_systemd_name }}"
    state: restarted
    daemon_reload: yes
  when: svc_enabled

- name: reload {{ svc_name }}
  systemd:
    name: "{{ svc_systemd_name }}"
    state: reloaded
  when: svc_enabled
